version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerBackendFile
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./community-learning-hub
      dockerfile: DockerFrontendFile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
